# Copyright (c) 2021 Autodesk, Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the ShotGrid Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the ShotGrid Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Autodesk, Inc.
#

description: Apps and Engines when toolkit is run from outside a project.

#################################################################################################
# define all the items that should appear in this environment
# By default make the non-project side of the desktop engine available

engines:
  tk-rv:
    apps:
      tk-multi-pythonconsole:
        external_sources_hook: '{self}/external_sources.py'
        location:
          type: git_branch
          path: https://github.com/shotgunsoftware/tk-multi-pythonconsole.git
          branch: ticket/SG-34329-rebranding
          version: 9ccaedbbceffda0bf09c0b52294c221027e0381c
      tk-multi-importcut:
        cut_link_field: sg_entity
        default_head_in: 1001
        default_head_in_duration: 8
        default_tail_out_duration: 8
        display_name: Import Cut
        ensure_sg_setup_hook: '{self}/post_install.py'
        location:
          type: git_branch
          path: https://github.com/shotgunsoftware/tk-multi-importcut.git
          branch: ticket/SG-34324-rebranding
          version: 36818dbf29c0484fd8637f8fd92e9e5a297850f3
        omit_statuses: [inac, hld, omt]
        reinstate_status: ip
        report_to_group: Editorial
        sg_cut_item_entity: CutItem
        use_smart_fields: true
        timecode_frame_mapping:
          timecode: automatic
          frame: 1001
    menu_overrides:
      Tools:
      - {app_instance: tk-multi-pythonconsole, name: PTR Python Console...}
    debug_logging: false
    location:
      type: git_branch
      path: https://github.com/shotgunsoftware/tk-rv.git
      branch: ticket/SG-34313-rebranding
      version: 34b826de54d6b96119ffdbc4fd51cf26c965c9e9

frameworks:
  tk-framework-qtwidgets_v2.x.x: # Used by shotgunreview and importcut
    location:
      type: git_branch
      path: https://github.com/shotgunsoftware/tk-framework-qtwidgets.git
      branch: ticket/SG-34303-rebranding
      version: 25d6fb4ab99384aed91bcdf7beaffcbc77062680
  tk-framework-shotgunutils_v5.x.x:  # Used for pythonconsole and importcut
    location:
      type: git_branch
      path: https://github.com/shotgunsoftware/tk-framework-shotgunutils.git
      branch: ticket/SG-34304-rebranding
      version: 1aaf07bb1c660ae3fa9d0a2bf8ca986c5c680242
  tk-framework-editorial_v2.x.x: # Used by importcut
    location:
      type: git_branch
      path: https://github.com/shotgunsoftware/tk-framework-editorial.git
      branch: ticket/SG-34301-rebranding
      version: 04355d8ac99903d0fec613d5489a821fbf343de0
