# Copyright (c) 2021 Autodesk, Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the ShotGrid Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the ShotGrid Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Autodesk, Inc.
#

description: Apps and Engines when toolkit is run from outside a project.

#################################################################################################
# define all the items that should appear in this environment
# By default make the non-project side of the desktop engine available

engines:
  tk-rv:
    apps:
      tk-multi-pythonconsole:
        external_sources_hook: '{self}/external_sources.py'
        location:
          type: app_store
          name: tk-multi-pythonconsole
          version: v1.4.2
      tk-multi-importcut:
        cut_link_field: sg_entity
        default_head_in: 1001
        default_head_in_duration: 8
        default_tail_out_duration: 8
        display_name: Import Cut
        ensure_sg_setup_hook: '{self}/post_install.py'
        location:
          type: app_store
          name: tk-multi-importcut
          version: v2.5.0
        omit_statuses: [inac, hld, omt]
        reinstate_status: ip
        report_to_group: Editorial
        sg_cut_item_entity: CutItem
        use_smart_fields: true
        timecode_frame_mapping:
          timecode: automatic
          frame: 1001
    menu_overrides:
      Tools:
      - {app_instance: tk-multi-pythonconsole, name: PTR Python Console...}
    debug_logging: false
    location:
      type: app_store
      name: tk-rv
      version: v1.1.0

frameworks:
  tk-framework-qtwidgets_v2.x.x: # Used by shotgunreview and importcut
    location:
      type: app_store
      name: tk-framework-qtwidgets
      version: v2.12.5
  tk-framework-shotgunutils_v5.x.x:  # Used for pythonconsole and importcut
    location:
      name: tk-framework-shotgunutils
      type: app_store
      version: v5.10.1
  tk-framework-editorial_v2.x.x: # Used by importcut
    location:
      type: app_store
      name: tk-framework-editorial
      version: v2.3.0
